version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:10-jdk-node-browsers
    environment:
      - SONAR_SCANNER_VERSION: "3.2.0.1227"
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: sudo npm install -g npm
      - run: sudo npm install -g greenkeeper-lockfile@2
      - run: greenkeeper-lockfile-update
      - run: npm install
      - run: npm run build
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: mkdir test/outputs
      - run: npm test
      - run:
          name: analyze by SonarScanner
          command: bash ./.circleci/sonar-scanner.sh
      - run: greenkeeper-lockfile-upload
